/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ikayaki_core_JNITest */

#ifndef _Included_ikayaki_core_JNITest
#define _Included_ikayaki_core_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ikayaki_core_JNITest
 * Method:    helloC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ikayaki_core_JNITest_helloC
  (JNIEnv *, jclass);

/*
 * Class:     ikayaki_core_JNITest
 * Method:    getDouble
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ikayaki_core_JNITest_getDouble
  (JNIEnv *, jclass);

/*
 * Class:     ikayaki_core_JNITest
 * Method:    getArray
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_ikayaki_core_JNITest_getArray
  (JNIEnv *, jclass, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
