//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PAcquire.rc
//
#define IDI_Vector                      101
#define IDI_APS_Logo                    102
#define Axes_Dialog                     103
#define Configure_Dialog                104
#define Handler_Dialog                  105
#define Demagnetizer_Dialog             106
#define Magnetometer_Dialog             107
#define MeasureSingle_Dialog            108
#define MeasureSequence_Dialog          109
#define Measure_Dialog                  110
#define Sample_Dialog                   111
#define MeasureSample_Dialog            112
#define MeasureStandard_Dialog          113
#define Cancel_Dialog                   114
#define SampleHandlerMove_Dialog        115
#define About_Dialog                    116
#define Orientation_Dialog              117
#define RangeUp_Dialog                  118
#define IDR_MainMenu                    119
#define IDI_EinBeck                     120
#define IDB_2GEnterprises               121
#define IDD_CONFIG_X                    1001
#define IDD_CONFIG_Y                    1002
#define IDD_CONFIG_Z                    1003
#define IDD_CONFIG_CALIB                1004
#define IDD_CONFIG_DCSQUIDS             1005
#define IDD_CONFIG_AFAUTO               1006
#define IDD_CONFIG_AFMAN                1007
#define IDD_CONFIG_AFNONE               1008
#define IDD_CONFIG_PARAM                1009
#define IDD_CONFIG_SHAUTO               1010
#define IDD_CONFIG_SHMAN                1011
#define IDD_CONFIG_POS                  1012
#define IDD_CONFIG_MAG                  1013
#define IDD_CONFIG_MAGCOM               1014
#define IDD_CONFIG_AF                   1015
#define IDD_CONFIG_AFCOM                1016
#define IDD_CONFIG_SH                   1017
#define IDD_CONFIG_SHCOM                1018
#define IDD_CONFIG_ORIENT               1019
#define IDD_CONFIG_OK                   1020
#define IDD_CALIB_XGROUP                1021
#define IDD_CALIB_XCALIB                1022
#define IDD_CALIB_X                     1023
#define IDD_CALIB_XEMU                  1024
#define IDD_CALIB_YGROUP                1025
#define IDD_CALIB_YCALIB                1026
#define IDD_CALIB_Y                     1027
#define IDD_CALIB_YEMU                  1028
#define IDD_CALIB_ZGROUP                1029
#define IDD_CALIB_ZCALIB                1030
#define IDD_CALIB_Z                     1031
#define IDD_CALIB_ZEMU                  1032
#define IDD_CALIB_OK                    1033
#define IDD_HANDLER_2G810               1034
#define IDD_HANDLER_2G811               1035
#define IDD_HANDLER_TRANS               1036
#define IDD_HANDLER_ROT                 1037
#define IDD_HANDLER_FLIP                1038
#define IDD_HANDLER_NOFLIP              1039
#define IDD_HANDLER_ACCELT              1040
#define IDD_HANDLER_ACCEL               1041
#define IDD_HANDLER_DECELT              1042
#define IDD_HANDLER_DECEL               1043
#define IDD_HANDLER_VELT                1044
#define IDD_HANDLER_VEL                 1045
#define IDD_HANDLER_VELMT               1046
#define IDD_HANDLER_VELM                1047
#define IDD_HANDLER_POS                 1048
#define IDD_HANDLER_POSTRANSXT          1049
#define IDD_HANDLER_POSTRANSX           1050
#define IDD_HANDLER_POSTRANSYT          1051
#define IDD_HANDLER_POSTRANSY           1052
#define IDD_HANDLER_POSAXIALT           1053
#define IDD_HANDLER_POSAXIAL            1054
#define IDD_HANDLER_POSLOADT            1055
#define IDD_HANDLER_POSLOAD             1056
#define IDD_HANDLER_POSBACKT            1057
#define IDD_HANDLER_POSBACK             1058
#define IDD_HANDLER_POSMEAST            1059
#define IDD_HANDLER_POSMEAS             1060
#define IDD_HANDLER_RIGHTT              1061
#define IDD_HANDLER_RIGHT               1062
#define IDD_HANDLER_ROTATION            1063
#define IDD_HANDLER_COUNTST             1064
#define IDD_HANDLER_COUNTS              1065
#define IDD_HANDLER_OK                  1066
#define IDD_DEMAG_X                     1067
#define IDD_DEMAG_Y                     1068
#define IDD_DEMAG_Z                     1069
#define IDD_DEMAG_2G601S                1070
#define IDD_DEMAG_2G601T                1071
#define IDD_DEMAG_FIELD                 1072
#define IDD_DEMAG_RAMP                  1073
#define IDD_HANDLER_ACCELT2             1073
#define IDD_DEMAG_DELAY                 1074
#define IDD_HANDLER_ACCEL2              1074
#define IDD_DEMAG_OK                    1075
#define IDD_HANDLER_DECELT2             1075
#define IDD_MAG_XGROUP                  1076
#define IDD_HANDLER_DECEL2              1076
#define IDD_MAG_XRANGET                 1077
#define IDD_HANDLER_VELT2               1077
#define IDD_MAG_XRANGE                  1078
#define IDD_HANDLER_VEL2                1078
#define IDD_MAG_XFLUX                   1079
#define IDD_MAG_XFILTERT                1080
#define IDD_MAG_XFILTER                 1081
#define IDD_MAG_XSLEW                   1082
#define IDD_MAG_XRESET                  1083
#define IDD_MAG_XPANEL                  1084
#define IDD_MAG_YGROUP                  1085
#define IDD_MAG_YRANGET                 1086
#define IDD_MAG_YRANGE                  1087
#define IDD_MAG_YFLUX                   1088
#define IDD_MAG_YFILTERT                1089
#define IDD_MAG_YFILTER                 1090
#define IDD_MAG_YSLEW                   1091
#define IDD_MAG_YRESET                  1092
#define IDD_MAG_YPANEL                  1093
#define IDD_MAG_ZGROUP                  1094
#define IDD_MAG_ZRANGET                 1095
#define IDD_MAG_ZRANGE                  1096
#define IDD_MAG_ZFLUX                   1097
#define IDD_MAG_ZFILTERT                1098
#define IDD_MAG_ZFILTER                 1099
#define IDD_MAG_ZSLEW                   1100
#define IDD_MAG_ZRESET                  1101
#define IDD_MAG_ZPANEL                  1102
#define IDD_MAG_DELAY                   1103
#define IDD_MAG_OK                      1104
#define IDD_SINGLE_AF                   1105
#define IDD_SINGLE_FIELD                1106
#define IDD_SINGLE_MT                   1107
#define IDD_SINGLE_THERMAL              1108
#define IDD_SINGLE_TEMP                 1109
#define IDD_SINGLE_NONE                 1110
#define IDD_SINGLE_OK                   1111
#define IDD_SEQUENCE_START              1112
#define IDD_SEQUENCE_INCREMENT1         1113
#define IDD_SEQUENCE_STOP1              1114
#define IDD_SEQUENCE_INCREMENT2         1115
#define IDD_SEQUENCE_STOP2              1116
#define IDD_SEQUENCE_OK                 1117
#define IDD_OPTIONS_XYZ                 1118
#define IDD_OPTIONS_XYZAVERAGE          1119
#define IDD_OPTIONS_MINIMUM             1120
#define IDD_OPTIONS_SINGLE              1121
#define IDD_OPTIONS_MULTIPLE            1122
#define IDD_OPTIONS_ROTATIONS           1123
#define IDD_OPTIONS_SNTHRESHOLD         1124
#define IDD_OPTIONS_SNREMEASURE         1125
#define IDD_OPTIONS_SNNOTIFY            1126
#define IDD_OPTIONS_DRIFTTHRESHOLD      1127
#define IDD_OPTIONS_DRIFTREMEASURE      1128
#define IDD_OPTIONS_DRIFTNOTIFY         1129
#define IDD_OPTIONS_MEASUREZ            1130
#define IDD_OPTIONS_OK                  1131
#define IDD_SAMPLE_NAME                 1132
#define IDD_SAMPLE_SIZE                 1133
#define IDD_SAMPLE_CC                   1134
#define IDD_SAMPLE_GM                   1135
#define IDD_SAMPLE_TIME                 1136
#define IDD_SAMPLE_COMMENT              1137
#define IDD_SAMPLE_COREAZ               1138
#define IDD_SAMPLE_COREPL               1139
#define IDD_SAMPLE_BEDAZ                1140
#define IDD_SAMPLE_BEDPL                1141
#define IDD_SAMPLE_BEDOVER              1142
#define IDD_SAMPLE_FOLDAZ               1143
#define IDD_SAMPLE_FOLDPL               1144
#define IDD_SAMPLE_DECL                 1145
#define IDD_SAMPLE_OK                   1146
#define IDD_HOLDER_X                    1147
#define IDD_HOLDER_Y                    1148
#define IDD_HOLDER_Z                    1149
#define IDD_HOLDER_TOTAL                1150
#define IDD_HOLDER_CLEAR                1151
#define IDD_STANDARD_X                  1152
#define IDD_STANDARD_Y                  1153
#define IDD_STANDARD_Z                  1154
#define IDD_STANDARD_TOTAL              1155
#define IDD_STANDARD_ANGLE              1156
#define IDD_STANDARD_CLEAR              1157
#define IDD_OK_MEASURE                  1158
#define IDD_CANCEL_MEASURE              1159
#define IDD_MOVE_TRANST                 1160
#define IDD_MOVE_TRANS                  1161
#define IDD_MOVE_ROTT                   1162
#define IDD_MOVE_ROT                    1163
#define IDD_MOVE_OK                     1164
#define IDD_ORIENT_COREAZ               1165
#define IDD_ORIENT_COREPCOMP            1166
#define IDD_ORIENT_COREPSIGN            1167
#define IDD_ORIENT_BEDDINGAZ            1168
#define IDD_ORIENT_BEDDINGPCOMP         1169
#define IDD_ORIENT_BEDDINGPSIGN         1170
#define IDD_ORIENT_FOLDAZ               1171
#define IDD_ORIENT_FOLDPCOMP            1172
#define IDD_ORIENT_FOLDPSIGN            1173
#define IDD_ORIENT_OK                   1174
#define IDC_PATH                        1175
#define IDM_FILE_NEW                    40001
#define IDM_FILE_OPEN                   40002
#define IDM_FILE_SAVE                   40003
#define IDM_FILE_SAVEAS                 40004
#define IDM_FILE_PRINT                  40005
#define IDM_FILE_SETUP                  40006
#define IDM_FILE_CONFIGURE              40007
#define IDM_FILE_EXIT                   40008
#define IDM_WINDOW_ICONS                40009
#define IDM_WINDOW_TILEHORIZONTALLY     40010
#define IDM_WINDOW_TILEVERTICALLY       40011
#define IDM_WINDOW_CASCADE              40012
#define IDM_WINDOW_CLOSEALL             40013
#define IDM_MAG_SETTINGS                40014
#define IDM_SH_MOVE                     40015
#define IDM_MEASURE_SINGLE              40016
#define IDM_MEASURE_SEQUENCE            40017
#define IDM_MEASURE_HOLDER              40018
#define IDM_MEASURE_STANDARD            40019
#define IDM_MEASURE_OPTIONS             40020
#define IDM_HELP_ABOUT                  40021

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        122
#define _APS_NEXT_COMMAND_VALUE         40024
#define _APS_NEXT_CONTROL_VALUE         1176
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
