#!/bin/bash
# super-commit-all-script; run with no arguments for help

if [ -z "$1" ]; then
	echo "super-commit-all-script, does the following:"
	echo "1) appends date, phase code, hours and message to"
	echo "   /home/group/squid/public_html/$USER/hours.txt"
	echo "2) appends message to ./versio.tex (without version or date)"
	echo "3) executes 'cvs commit -m \"message\"'"
	echo
	echo usage: $0 "message" [hours] [phase code]
	echo exmpl: $0 \"added some stuff\" 2,5 SU
	exit 1
fi

hourfile=/home/group/squid/public_html/$USER/hours.txt
verfile=./versio.tex

if [ ! -w $hourfile ]; then
	echo $0: \'$hourfile\' missing or not writable > /dev/stderr
	exit 2
fi

if [ ! -w $verfile ]; then
	echo $0: \'$verfile\' missing or not writable > /dev/stderr
	exit 2
fi

date=$(date +%-d.%-m.%Y)
code=$3
hours=$2
msg=$1

echo $date$'\t'$code$'\t'$hours$'\t'$msg >> $hourfile &&
echo $'\t\t'\&\& $msg >> $verfile &&
cvs commit -m "$msg"
